forgot to commit for a while

diff --git a/zsh/zshrc b/zsh/zshrc
--- a/zsh/zshrc
+++ b/zsh/zshrc
@@ -2,11 +2,51 @@ ZSH_HOME=$HOME/etc/zsh
 
 DEFAULT_USER=$(whoami)
 
-# paths
-source $ZSH_HOME/paths.zsh
 
-# functions
-source $ZSH_HOME/functions.zsh
+# --------------------------------------------------------------------------------------------------
+#
+#                                           Paths
+#
+# --------------------------------------------------------------------------------------------------
+
+
+path=(
+~/anaconda/bin
+~/go/bin
+/usr/local/bin
+/usr/local/sbin
+~/local/bin
+~/etc/bin
+~/local/sbin
+/usr/local/sbin
+/usr/local/cuda/bin
+/usr/X11/bin
+/usr/bin
+/usr/sbin
+/usr/texbin
+/bin
+/sbin
+$PATH
+)
+
+manpath=(
+$MANPATH
+/usr/man
+/usr/share/man
+/usr/local/share/man
+/usr/local/git/man
+~/local/man/
+)
+
+fpath=($ZSH_HOME/completions $fpath)
+
+export NODE_PATH=$NODE_PATH:/usr/local/lib/node
+export GOPATH=$HOME/go
+
+
+export EVOLVERPATH=$HOME/Documents/Research/Evolver/fe:$HOME/Documents/Research/Evolver/doc
+export PYTHONPATH=$HOME/local/python:$HOME/anaconda/bin:$PYTHONPATH
+
 
 ## useful remnants of OMZ
 # git, theming, completions
@@ -14,11 +54,6 @@ source $ZSH_HOME/functions.zsh
 source $ZSH_HOME/OMZ_remnants.zsh
 
 
-# my theme :)
-source $ZSH_HOME/redacted-mh.zsh-theme
-
-# aliases
-source $ZSH_HOME/aliases.zsh
 
 # fasd
 # only init if installed.
@@ -37,9 +72,6 @@ fi
 # tmuxinator
 [[ -s $HOME/.tmuxinator/scripts/tmuxinator ]] && source $HOME/.tmuxinator/scripts/tmuxinator
 
-# grc
-source "`brew --prefix`/etc/grc.bashrc"
-
 ## Zsh options
 setopt auto_name_dirs
 setopt pushd_ignore_dups
@@ -56,8 +88,6 @@ autoload -U compinit
 compinit -i
 
 export SHELL=zsh
-export RPS1='$(battery_pct_prompt)'
-export RPROMPT='$(battery_pct_prompt)''$(git_prompt_info)'
 export EDITOR=/usr/local/bin/vim
 export PAGER="less"
 export LESS="-R"
@@ -87,14 +117,17 @@ alias mv='nocorrect mv'
 alias mkdir='nocorrect mkdir'
 alias sudo='nocorrect sudo'
 
+
+## online help
+unalias run-help
+autoload run-help
+HELPDIR=/usr/local/share/zsh/helpfiles
+
+
 ## Edit command line
 autoload -U edit-command-line
 zle -N edit-command-line
 bindkey '\C-x\C-e' edit-command-line
-
-## smart urls
-autoload -U url-quote-magic
-zle -N self-insert url-quote-magic
 
 ## file rename magick
 bindkey "^[m" copy-prev-shell-word
@@ -134,24 +167,300 @@ bindkey "^[3;5~" delete-char
 bindkey "\e[3~" delete-char
 
 
-# syntax highlighting (must be at the end!)
-source $ZSH_HOME/syntax-highlighting/zsh-syntax-highlighting.zsh
 
-# search (must be after syntax :-)
-source $ZSH_HOME/history-substring-search/zsh-history-substring-search.zsh
 
-## substring search config
-for keycode in '[' '0'; do
-    bindkey "^[${keycode}A" history-substring-search-up
-    bindkey "^[${keycode}B" history-substring-search-down
-done
+# --------------------------------------------------------------------------------------------------
+#
+#                                           Aliases
+#
+# --------------------------------------------------------------------------------------------------
 
-unset keycode
+alias mmv="noglob zmv -W" # change extension
 
-# bind P and N for EMACS mode
-bindkey -M emacs '^P' history-substring-search-up
-bindkey -M emacs '^N' history-substring-search-down
+alias clj='rlwrap clj'
+alias evolver='rlwrap evolver'
+alias evolver_orig='~/local/bin/evolver'
 
-# bind k and j for VI mode
-bindkey -M vicmd 'k' history-substring-search-up
-bindkey -M vicmd 'j' history-substring-search-down
+
+alias socks-tunnel="ssh -D 9999 netsoc"
+alias work-git="source ~/etc/bin/work" # need to set up a socks proxy localhost:9999 to work!
+alias mountvm="sshfs steven@ubuntu.local:/home/steven ~/mnt/ubuntuVM -oauto_cache,reconnect,volname=ubuntuVM"
+
+alias lsa='ls -lah'
+#alias l='ls -la'
+alias ll='ls -l'
+alias la='ls -lA'
+alias sl=ls # often screw this up
+
+# Will cd into the top of the current repository
+# or submodule.
+alias grt='cd $(git rev-parse --show-toplevel || echo ".")'
+
+# fasd
+# jump to recently used items
+alias a='fasd -a' # any
+alias s='fasd -si' # show / search / select
+alias d='fasd -d' # directory
+alias f='fasd -f' # file
+alias z='fasd_cd -d' # cd, same functionality as j in autojump
+alias zz='fasd_cd -d -i' # interactive directory jump
+alias fst="fasd -a -e 'subl -n'"
+alias o='a-e open'
+
+
+# --------------------------------------------------------------------------------------------------
+#
+#                                           Functions
+#
+# --------------------------------------------------------------------------------------------------
+
+
+quit () {
+        for app in $*; do
+                osascript -e 'quit app "'$app'"'
+        done
+}
+
+relaunch () {
+        for app in $*; do
+                osascript -e 'quit app "'$app'"';
+                open -a $app
+        done
+}
+
+# display processes tree in less
+pst ()
+{
+    local pid
+    pid=$(ps -ax | grep $1 | grep -v grep | awk '{ print $1 }')
+    pstree -p $pid  | less -S
+}
+
+# search for various types or README file in dir and display them in $PAGER
+readme ()
+{
+    local files
+    files=(./(#i)*(read*me|lue*m(in|)ut)*(ND))
+    if (($#files))
+        then $EDITOR $files
+    else
+        print 'No README files.'
+    fi
+}
+
+# Display image with tput
+function image() {
+  convert "$1" -resize 40 txt:-|sed -E 's/://;s/\( ? ?//;s/, ? ?/,/g;s/\)//;s/(\w,\w,\w),\w/\1/g;/mage/d'|awk '{print $1,$2}'|python -c "import sys;f=sys.stdin.read().split('\n');f=filter(None,f);print 'tput rev;'+''.join([''.join(map(str,('echo;' if x.split(' ')[0].split(',')[0] is '0' else '','tput setaf '+str(sum(p*q for p,q in zip([36,6,1],[int(min(int(c),254)/42.5) for c in x.split(' ')[1].split(',')]))+16)+';echo -n \"  \";'))) for x in f])+'echo;tput sgr0'"|bash
+}
+
+# man pages in preview
+function man-preview() {
+  man -t "$@" | open -f -a Preview
+}
+
+
+function copydir {
+  pwd | tr -d "\r\n" | pbcopy
+}
+
+function copyfile {
+  [[ "$#" != 1 ]] && return 1
+  local file_to_copy=$1
+  cat $file_to_copy | pbcopy
+}
+
+###########################################
+# Battery plugin for oh-my-zsh            #
+###########################################
+
+  function battery_pct() {
+    typeset -F maxcapacity=$(ioreg -rc "AppleSmartBattery"| grep '^.*"MaxCapacity"\ =\ ' | sed -e 's/^.*"MaxCapacity"\ =\ //')
+    typeset -F currentcapacity=$(ioreg -rc "AppleSmartBattery"| grep '^.*"CurrentCapacity"\ =\ ' | sed -e 's/^.*CurrentCapacity"\ =\ //')
+    integer i=$(((currentcapacity/maxcapacity) * 100))
+    echo $i
+  }
+
+  function battery_pct_remaining() {
+    if [[ $(ioreg -rc AppleSmartBattery | grep -c '^.*"ExternalConnected"\ =\ No') -eq 1 ]] ; then
+      battery_pct
+    else
+      echo "External Power"
+    fi
+  }
+
+  function battery_time_remaining() {
+    if [[ $(ioreg -rc AppleSmartBattery | grep -c '^.*"ExternalConnected"\ =\ No') -eq 1 ]] ; then
+      timeremaining=$(ioreg -rc "AppleSmartBattery"| grep '^.*"AvgTimeToEmpty"\ =\ ' | sed -e 's/^.*"AvgTimeToEmpty"\ =\ //')
+      echo "~$((timeremaining / 60)):$((timeremaining % 60))"
+    else
+      echo "∞"
+    fi
+  }
+
+  function battery_pct_prompt () {
+    if [[ $(ioreg -rc AppleSmartBattery | grep -c '^.*"ExternalConnected"\ =\ No') -eq 1 ]] ; then
+      b=$(battery_pct_remaining)
+      if [ $b -gt 50 ] ; then
+        color='green'
+      elif [ $b -gt 20 ] ; then
+        color='yellow'
+      else
+        color='red'
+      fi
+      echo "%{$fg[$color]%}[$(battery_pct_remaining)%%]%{$reset_color%}"
+    else
+      echo "∞"
+    fi
+  }
+
+function extract() {
+  local remove_archive
+  local success
+  local file_name
+  local extract_dir
+
+  if (( $# == 0 )); then
+    echo "Usage: extract [-option] [file ...]"
+    echo
+    echo Options:
+    echo "    -r, --remove    Remove archive."
+    echo
+    echo "Report bugs to <sorin.ionescu@gmail.com>."
+  fi
+
+  remove_archive=1
+  if [[ "$1" == "-r" ]] || [[ "$1" == "--remove" ]]; then
+    remove_archive=0
+    shift
+  fi
+
+  while (( $# > 0 )); do
+    if [[ ! -f "$1" ]]; then
+      echo "extract: '$1' is not a valid file" 1>&2
+      shift
+      continue
+    fi
+
+    success=0
+    file_name="$( basename "$1" )"
+    extract_dir="$( echo "$file_name" | sed "s/\.${1##*.}//g" )"
+    case "$1" in
+      (*.tar.gz|*.tgz) tar xvzf "$1" ;;
+      (*.tar.bz2|*.tbz|*.tbz2) tar xvjf "$1" ;;
+      (*.tar.xz|*.txz) tar --xz --help &> /dev/null \
+        && tar --xz -xvf "$1" \
+        || xzcat "$1" | tar xvf - ;;
+      (*.tar.zma|*.tlz) tar --lzma --help &> /dev/null \
+        && tar --lzma -xvf "$1" \
+        || lzcat "$1" | tar xvf - ;;
+      (*.tar) tar xvf "$1" ;;
+      (*.gz) gunzip "$1" ;;
+      (*.bz2) bunzip2 "$1" ;;
+      (*.xz) unxz "$1" ;;
+      (*.lzma) unlzma "$1" ;;
+      (*.Z) uncompress "$1" ;;
+      (*.zip) unzip "$1" -d $extract_dir ;;
+      (*.rar) unrar x -ad "$1" ;;
+      (*.7z) 7za x "$1" ;;
+      (*.deb)
+        mkdir -p "$extract_dir/control"
+        mkdir -p "$extract_dir/data"
+        cd "$extract_dir"; ar vx "../${1}" > /dev/null
+        cd control; tar xzvf ../control.tar.gz
+        cd ../data; tar xzvf ../data.tar.gz
+        cd ..; rm *.tar.gz debian-binary
+        cd ..
+      ;;
+      (*)
+        echo "extract: '$1' cannot be extracted" 1>&2
+        success=1
+      ;;
+    esac
+
+    (( success = $success > 0 ? $success : $? ))
+    (( $success == 0 )) && (( $remove_archive == 0 )) && rm "$1"
+    shift
+  done
+}
+
+## Git OMZ
+function current_branch() {
+  ref=$(git symbolic-ref HEAD 2> /dev/null) || \
+  ref=$(git rev-parse --short HEAD 2> /dev/null) || return
+  echo ${ref#refs/heads/}
+}
+
+function current_repository() {
+  ref=$(git symbolic-ref HEAD 2> /dev/null) || \
+  ref=$(git rev-parse --short HEAD 2> /dev/null) || return
+  echo $(git remote -v | cut -d':' -f 2)
+}
+
+# Pretty log messages
+function _git_log_prettily(){
+  if ! [ -z $1 ]; then
+    git log --pretty=$1
+  fi
+}
+alias glp="_git_log_prettily"
+
+## Mercurial OMZ
+function hg_current_branch() {
+  if [ -d .hg ]; then
+    echo hg:$(hg branch)
+  fi
+}
+
+function title() {
+    # escape '%' chars in $1, make nonprintables visible
+    local a=${(V)1//\%/\%\%}
+
+    # Truncate command, and join lines.
+    a=$(print -Pn "%40>...>$a" | tr -d "\n")
+    case $TERM in
+        screen*)
+            print -Pn "\e]2;$a @ $2\a" # plain xterm title
+            print -Pn "\ek$a\e\\"      # screen title (in ^A")
+            print -Pn "\e_$2   \e\\"   # screen location
+            ;;
+        xterm*)
+            print -Pn "\e]2;$a @ $2\a" # plain xterm title
+            ;;
+    esac
+}
+
+# precmd is called just before the prompt is printed
+function precmd() {
+    title "zsh" "%m:%55<...<%~"
+    # _z --add "$(pwd -P)"
+    print -Pn "\e]0;%~\a"
+}
+
+# preexec is called just before any command line is executed
+function preexec() {
+    title "$1" "%m:%35<...<%~"
+}
+
+
+
+# --------------------------------------------------------------------------------------------------
+#
+#                                           Theming
+#
+# --------------------------------------------------------------------------------------------------
+
+# mh theme edited by redacted
+
+# prompt
+PROMPT='[%{$fg[red]%}%30<...<%~%<<%{$reset_color%}]%(!.#.$) '
+RPROMPT='$(git_prompt_info)''$(battery_pct_prompt)'
+
+# git theming
+ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg_bold[gray]%}(%{$fg_no_bold[yellow]%}%B"
+ZSH_THEME_GIT_PROMPT_SUFFIX="%b%{$fg_bold[gray]%})%{$reset_color%} "
+ZSH_THEME_GIT_PROMPT_CLEAN=""
+ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg_bold[red]%}✱"
+
+# LS colors, made with http://geoff.greer.fm/lscolors/
+export LSCOLORS="Gxfxcxdxbxegedabagacad"
+export LS_COLORS='no=00:fi=00:di=01;34:ln=00;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=41;33;01:ex=00;32:*.cmd=00;32:*.exe=01;32:*.com=01;32:*.bat=01;32:*.btm=01;32:*.dll=01;32:*.tar=00;31:*.tbz=00;31:*.tgz=00;31:*.rpm=00;31:*.deb=00;31:*.arj=00;31:*.taz=00;31:*.lzh=00;31:*.lzma=00;31:*.zip=00;31:*.zoo=00;31:*.z=00;31:*.Z=00;31:*.gz=00;31:*.bz2=00;31:*.tb2=00;31:*.tz2=00;31:*.tbz2=00;31:*.avi=01;35:*.bmp=01;35:*.fli=01;35:*.gif=01;35:*.jpg=01;35:*.jpeg=01;35:*.mng=01;35:*.mov=01;35:*.mpg=01;35:*.pcx=01;35:*.pbm=01;35:*.pgm=01;35:*.png=01;35:*.ppm=01;35:*.tga=01;35:*.tif=01;35:*.xbm=01;35:*.xpm=01;35:*.dl=01;35:*.gl=01;35:*.wmv=01;35:*.aiff=00;32:*.au=00;32:*.mid=00;32:*.mp3=00;32:*.ogg=00;32:*.voc=00;32:*.wav=00;32:'
